/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import java.math.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class CollectConfigMessage {

	@NotNull
	@Size(min=8, max=8)
	@Component(0)
	public byte[] msgid;

	@NotNull
	@Min(0L) @Max(1000000L)
	@Component(1)
	public Integer collectFrequency;

	@NotNull
	@Min(0L) @Max(1000000L)
	@Component(2)
	public Integer sendFrequency;


	public Object clone() {
		return TYPE.clone(this, CONV);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof CollectConfigMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static CollectConfigMessage ber_decode(InputStream in) throws IOException {
		return (CollectConfigMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}

	public void cer_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.CANONICAL_ENCODING_RULES, CONV, out);
	}

	public static CollectConfigMessage cer_decode(InputStream in) throws IOException {
		return (CollectConfigMessage)TYPE.decode(in, EncodingRules.CANONICAL_ENCODING_RULES, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static CollectConfigMessage der_decode(InputStream in) throws IOException {
		return (CollectConfigMessage)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}

	public void per_encode(boolean align, OutputStream out) throws IOException {
		TYPE.encode(this, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
	}

	public static CollectConfigMessage per_decode(boolean align, InputStream in) throws IOException {
		return (CollectConfigMessage)TYPE.decode(in, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65543);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(CollectConfigMessage.class);
		AsnConverter msgidConverter = OctetStringConverter.INSTANCE;
		AsnConverter collectFrequencyConverter = IntegerConverter.INSTANCE;
		AsnConverter sendFrequencyConverter = IntegerConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgidConverter, collectFrequencyConverter, sendFrequencyConverter });
	}


}
