/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import java.math.*;
import java.util.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class LoginResponseMessage {

	@NotNull
	@Component(0)
	public Long msgCnt;

	@NotNull
	@Size(min=8, max=8)
	@Component(1)
	public byte[] vid;

	@NotNull
	@Component(2)
	public Boolean loginResult;

	@NotNull
	@Size(min=8, max=8)
	@Component(3)
	public byte[] token;

	@NotNull
	@Component(4)
	public byte[] errorCode;

	@NotNull
	@Component(5)
	public Vector<CollectConfigMessage> collectConfs;

	@NotNull
	@Component(6)
	public byte[] timestamp;

	@NotNull
	@Component(7)
	public Long syncNum;

	@NotNull
	@Component(8)
	public byte[] ciphertextThatRsaPublicKeyEncryptAesSecretKey;


	public Object clone() {
		return TYPE.clone(this, CONV);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof LoginResponseMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static LoginResponseMessage ber_decode(InputStream in) throws IOException {
		return (LoginResponseMessage)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}

	public void cer_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.CANONICAL_ENCODING_RULES, CONV, out);
	}

	public static LoginResponseMessage cer_decode(InputStream in) throws IOException {
		return (LoginResponseMessage)TYPE.decode(in, EncodingRules.CANONICAL_ENCODING_RULES, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static LoginResponseMessage der_decode(InputStream in) throws IOException {
		return (LoginResponseMessage)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}

	public void per_encode(boolean align, OutputStream out) throws IOException {
		TYPE.encode(this, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
	}

	public static LoginResponseMessage per_decode(boolean align, InputStream in) throws IOException {
		return (LoginResponseMessage)TYPE.decode(in, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65544);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(LoginResponseMessage.class);
		AsnConverter msgCntConverter = LongConverter.INSTANCE;
		AsnConverter vidConverter = OctetStringConverter.INSTANCE;
		AsnConverter loginResultConverter = BooleanConverter.INSTANCE;
		AsnConverter tokenConverter = OctetStringConverter.INSTANCE;
		AsnConverter errorCodeConverter = ResponseErrorCode.CONV;
		AsnConverter collectConfsConverter = new VectorConverter(CollectConfigMessage.CONV);
		AsnConverter timestampConverter = TimeStamp.CONV;
		AsnConverter syncNumConverter = LongConverter.INSTANCE;
		AsnConverter ciphertextThatRsaPublicKeyEncryptAesSecretKeyConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { msgCntConverter, vidConverter, loginResultConverter, tokenConverter, errorCodeConverter, collectConfsConverter, timestampConverter, syncNumConverter, ciphertextThatRsaPublicKeyEncryptAesSecretKeyConverter });
	}


}
