/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import java.math.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class Other {

	@NotNull
	@Component(0)
	public Double outsidetemp;

	@NotNull
	@Component(1)
	public HANDBRAKE handbrake;

	@NotNull
	@Component(2)
	public AutoHorn autohorn;

	@NotNull
	@Min(0L) @Max(4L)
	@Component(3)
	public Integer isautodrive;

	@NotNull
	@Size(min=8, max=8)
	@Component(4)
	public byte[] faultcode;


	public Object clone() {
		return TYPE.clone(this, CONV);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof Other)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static Other ber_decode(InputStream in) throws IOException {
		return (Other)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}

	public void cer_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.CANONICAL_ENCODING_RULES, CONV, out);
	}

	public static Other cer_decode(InputStream in) throws IOException {
		return (Other)TYPE.decode(in, EncodingRules.CANONICAL_ENCODING_RULES, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static Other der_decode(InputStream in) throws IOException {
		return (Other)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}

	public void per_encode(boolean align, OutputStream out) throws IOException {
		TYPE.encode(this, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
	}

	public static Other per_decode(boolean align, InputStream in) throws IOException {
		return (Other)TYPE.decode(in, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65578);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Other.class);
		AsnConverter outsidetempConverter = DoubleConverter.INSTANCE;
		AsnConverter handbrakeConverter = HANDBRAKE.CONV;
		AsnConverter autohornConverter = AutoHorn.CONV;
		AsnConverter isautodriveConverter = IntegerConverter.INSTANCE;
		AsnConverter faultcodeConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { outsidetempConverter, handbrakeConverter, autohornConverter, isautodriveConverter, faultcodeConverter });
	}


}
