/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "Platoon"
 */
package com.iot.nero.smartcan.entity.platoon;

import java.io.*;
import java.math.*;
import javax.validation.constraints.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class Wiper {

	@NotNull
	@Component(0)
	public FRONTWIPERSWITCH frontwiperwitch;

	@NotNull
	@Component(1)
	public Long frontwiperintermswitch;

	@NotNull
	@Component(2)
	public REARWIPER rearwiper;

	@NotNull
	@Component(3)
	public WINWASHFLUID winWashFluid;


	public Object clone() {
		return TYPE.clone(this, CONV);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof Wiper)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONV, out);
	}

	public void ber_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
	}

	public static Wiper ber_decode(InputStream in) throws IOException {
		return (Wiper)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
	}

	public void cer_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.CANONICAL_ENCODING_RULES, CONV, out);
	}

	public static Wiper cer_decode(InputStream in) throws IOException {
		return (Wiper)TYPE.decode(in, EncodingRules.CANONICAL_ENCODING_RULES, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static Wiper der_decode(InputStream in) throws IOException {
		return (Wiper)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}

	public void per_encode(boolean align, OutputStream out) throws IOException {
		TYPE.encode(this, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
	}

	public static Wiper per_decode(boolean align, InputStream in) throws IOException {
		return (Wiper)TYPE.decode(in, align? EncodingRules.ALIGNED_PACKED_ENCODING_RULES:EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Platoon.type(65552);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Wiper.class);
		AsnConverter frontwiperwitchConverter = FRONTWIPERSWITCH.CONV;
		AsnConverter frontwiperintermswitchConverter = LongConverter.INSTANCE;
		AsnConverter rearwiperConverter = REARWIPER.CONV;
		AsnConverter winWashFluidConverter = WINWASHFLUID.CONV;
		CONV.setComponentConverters(new AsnConverter[] { frontwiperwitchConverter, frontwiperintermswitchConverter, rearwiperConverter, winWashFluidConverter });
	}


}
